name: personalinformationsurvey
description: Personal Information Survey

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  load: ^1.0.0
  intl: ^0.17.0
  provider: ^5.0.0
  toggle_switch: ^1.2.0
  cupertino_icons: ^1.0.3
  flutter_rating_bar: ^4.0.0
  double_back_to_close: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
